# Generated by Django 2.2.24 on 2021-08-28 16:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bonos',
            fields=[
                ('bono_id', models.AutoField(primary_key=True, serialize=False)),
                ('bono_name', models.CharField(max_length=40, validators=[django.core.validators.MinLengthValidator(4)])),
                ('bono_number', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10000)])),
                ('bono_price', models.DecimalField(decimal_places=4, max_digits=9)),
            ],
            options={
                'ordering': ['bono_id'],
            },
        ),
    ]
