# Generated by Django 2.2.24 on 2021-08-29 03:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainbonos', '0002_bonos_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonos',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
