# Generated by Django 2.2.24 on 2021-08-29 03:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainbonos', '0003_auto_20210829_0309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonos',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
