# Generated by Django 2.2.24 on 2021-08-29 04:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainbonos', '0004_auto_20210829_0320'),
    ]

    operations = [
        migrations.AddField(
            model_name='bonos',
            name='bought_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='auth_user_id', to=settings.AUTH_USER_MODEL),
        ),
    ]
