# Generated by Django 2.2.24 on 2021-08-29 15:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainbonos', '0005_bonos_bought_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonos',
            name='bono_number',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100000000)]),
        ),
        migrations.AlterField(
            model_name='bonos',
            name='bono_price',
            field=models.DecimalField(decimal_places=4, max_digits=13),
        ),
    ]
