# Generated by Django 2.2.24 on 2021-08-29 15:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainbonos', '0006_auto_20210829_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonos',
            name='bono_number',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10000)]),
        ),
    ]
