# Generated by Django 2.2.24 on 2021-08-29 15:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainbonos', '0008_auto_20210829_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonos',
            name='bono_name',
            field=models.CharField(max_length=40, validators=[django.core.validators.MinLengthValidator(3)]),
        ),
    ]
